name: Backend Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run tests
      run: |
        cd backend
        # Add your test commands here
        # python -m pytest

    - name: Debug SSH Connection
      run: |
        echo "Testing SSH Connection..."
        ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo Connection Successful"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y python3 python3-pip python3-venv

          mkdir -p ~/portfolio-backend
          cd ~/portfolio-backend

          rm -rf VidyanshPortfolio
          git clone https://github.com/vidyansh07/VidyanshPortfolio.git
          cd VidyanshPortfolio/backend

          python3 -m venv venv
          source venv/bin/activate

          pip install -r requirements.txt
          mkdir -p ~/portfolio-backend/VidyanshPortfolio/backend/app/database

          sudo systemctl stop portfolio-backend || true

          sudo tee /etc/systemd/system/portfolio-backend.service > /dev/null <<SERVICE
          [Unit]
          Description=Portfolio Backend Service
          After=network.target

          [Service]
          User=ubuntu  # Replace with your EC2 username
          WorkingDirectory=/home/ubuntu/portfolio-backend/VidyanshPortfolio/backend
          Environment="DATABASE_PATH=/home/ubuntu/portfolio-backend/VidyanshPortfolio/backend/app/database/blog.db"
          ExecStart=/home/ubuntu/portfolio-backend/VidyanshPortfolio/backend/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000
          Restart=always

          [Install]
          WantedBy=multi-user.target
          SERVICE

          sudo systemctl daemon-reload
          sudo systemctl enable portfolio-backend
          sudo systemctl start portfolio-backend
        EOF

    - name: Verify Deployment
      run: |
        sleep 10
        curl ${{ secrets.EC2_HOST }}:8000/health || exit 1
